[pytest]
addopts = --doctest-glob='*.rst'
markers =
    api_mark
    automl_mark
    api_builds
    cli_mark
    client_mark
    managers_mark
    operators_mark
    polyaxonfile_mark
    polyflow_mark
    components_mark
    connections_mark
    workflow_mark
    container_mark
    environment_mark
    init_mark
    mounts_mark
    ops_mark
    sidecars_mark
    termination_mark
